basedir: ../outputs  # path to log directory
expname: pmavatar_s9 # log directly name

hydra:
    run:
        dir: "${basedir}/${expname}"

# dataset general
num_workers: 16
sampler:
  _target_: core.dataset.dataset.RayImageSampler

# hyperparameters
N_rays: 3072
N_sample_images: 16
iters: 300000 #300000
N_samples: 48
N_imporantce: 32

# logging
i_print: 400
i_save: 10000
i_testset: 10000 #10000
render_factor: 1 # factor to down size the rendered image during testing

trainer:
  optim: 
    _target_: torch.optim.Adam
    lr: 5e-4
  lr_sched:
    decay_steps: 500000 # steps to reach the desinated lr decay rate
    decay: 0.1
  
losses: ???

model: ???
dataset: ???
